### ISSUE TITLE
[Request] Make for linux also

### ISSUE THREAD

**Issue by hexdecimal16** [Snaacky/Diamond#10]
Please provide such scripts for linux

**Comment by Snaacky** [comment]
The library used for memory editing doesn't have Linux support. 

I'm not interested in adding Linux support to the library because it would target a rather niche community and I'm not interested in switching libraries because these repositories seem to be rather helpful to people trying to learn to use Pymem.

If that's something you're interested in, you could probably create a wrapper around `process_vm_writev` and `process_vm_readv` without too much effort.
