### ISSUE TITLE
can't run 

### ISSUE THREAD

**Issue by j1ans** [Snaacky/Diamond#4]
File "C:\Users\0000\AppData\Local\Programs\Python\Python37\lib\site-packages\p
ymem\__init__.py", line 476, in read_int
    value = pymem.memory.read_int(self.process_handle, address)
  File "C:\Users\0000\AppData\Local\Programs\Python\Python37\lib\site-packages\p
ymem\memory.py", line 271, in read_int
    bytes = read_bytes(handle, address, struct.calcsize('i'))
  File "C:\Users\0000\AppData\Local\Programs\Python\Python37\lib\site-packages\p
ymem\memory.py", line 105, in read_bytes
    raise pymem.exception.WinAPIError(error_code)
pymem.exception.WinAPIError: Windows api error, error_code: 299

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "diamond.py", line 42, in <module>
    main()
  File "diamond.py", line 23, in main
    entity_team_id = pm.read_int(entity + m_iTeamNum)
  File "C:\Users\0000\AppData\Local\Programs\Python\Python37\lib\site-packages\p
ymem\__init__.py", line 478, in read_int
    raise pymem.exception.MemoryReadError(address, struct.calcsize('i'), e.error
_code)
pymem.exception.MemoryReadError: Could not read memory at: 292, length: 4 - GetL
astError: 299

windows 7,python3.7 all install

**Comment by Snaacky** [comment]
My CS:GO repositories are not actively maintained because doing so would just inevitably result in enabling script kiddies to cheat in CS:GO. If you satisfy all the requirements and "update" this repository to match the latest version of the game, it will work as expected. I won't help you do that though.

All of my Python-based CS:GO cheat repositories serve two purposes: as a proof-of-concept demonstrating external memory editing in Python (which was relatively unexplored previously) and for others who are also using the Pymem library to use as an example/reference while working on their own projects because the library documentation isn't in the best of shape.
