### ISSUE TITLE
Don't work. glow_manager and entity are zero 

### ISSUE THREAD

**Issue by Your2Bwaify** [Snaacky/Diamond#6]

**Comment by Your2Bwaify** [comment]
And I had a series of questions. First how you get offsets using Python and second (little big stupid question) how it work? I'm newfag in winapi. Using Google i didn't found interesting information.(sorry for my eng it isnt my native language)

**Comment by Snaacky** [comment]
CS:GO has received 28 updates since the last push to this repository. 

Assuming there hasn't been a fundamental change to `dwGlowObjectManager`, this code base will still work if properly updated. However, I will not assist you in updating this repository to work with the latest version of CS:GO because I would be directly enabling people to cheat.
